//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoStudio.Client.PhotoStudioWcfService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PhotoStudioWcfService.IPhotoStudioService")]
    public interface IPhotoStudioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoStudioService/GetPhotos", ReplyAction="http://tempuri.org/IPhotoStudioService/GetPhotosResponse")]
        System.Collections.ObjectModel.Collection<PhotoStudio.Entities.Photo> GetPhotos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoStudioService/GetPhotos", ReplyAction="http://tempuri.org/IPhotoStudioService/GetPhotosResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<PhotoStudio.Entities.Photo>> GetPhotosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoStudioService/SubmitPrintOrder", ReplyAction="http://tempuri.org/IPhotoStudioService/SubmitPrintOrderResponse")]
        void SubmitPrintOrder(PhotoStudio.Entities.PrintOrder order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoStudioService/SubmitPrintOrder", ReplyAction="http://tempuri.org/IPhotoStudioService/SubmitPrintOrderResponse")]
        System.Threading.Tasks.Task SubmitPrintOrderAsync(PhotoStudio.Entities.PrintOrder order);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPhotoStudioServiceChannel : PhotoStudio.Client.PhotoStudioWcfService.IPhotoStudioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhotoStudioServiceClient : System.ServiceModel.ClientBase<PhotoStudio.Client.PhotoStudioWcfService.IPhotoStudioService>, PhotoStudio.Client.PhotoStudioWcfService.IPhotoStudioService {
        
        public PhotoStudioServiceClient() {
        }
        
        public PhotoStudioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhotoStudioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhotoStudioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhotoStudioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.ObjectModel.Collection<PhotoStudio.Entities.Photo> GetPhotos() {
            return base.Channel.GetPhotos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<PhotoStudio.Entities.Photo>> GetPhotosAsync() {
            return base.Channel.GetPhotosAsync();
        }
        
        public void SubmitPrintOrder(PhotoStudio.Entities.PrintOrder order) {
            base.Channel.SubmitPrintOrder(order);
        }
        
        public System.Threading.Tasks.Task SubmitPrintOrderAsync(PhotoStudio.Entities.PrintOrder order) {
            return base.Channel.SubmitPrintOrderAsync(order);
        }
    }
}
